- name: install and run Nodejs
  hosts: web
  become: yes
  tasks:
    - name: install Nodejs
      ansible.builtin.package:
      name: Nodejs
      state: present
    - name: start Nodejs
      ansible.builtin.sevice:
      name: Nodejs
      state: started