- name: install and run nodejs
  hosts: web
  become: yes
  tasks:
  - name: install nodejs
    ansible.buitin.packages:
    - name: nodejs
      state: present
  - name: install nodejs
    ansible.buitin.sevice:
    - name: nodejs
      state: started