- name: install and run node.js
  hosts: web
  become: yes
  tasks:
    - name: install node.js
      ansible.builtin.package:
        name: node.js
        state: present
    - name: start node.js
      ansible.builtin.service:
        name: node.js
        state: started