- name: Install and run MySQL
  hosts: web
  become: yes
  tasks:
    - name: Install MySQL server
      ansible.builtin.package:
        name: mysql-server
        state: present

    - name: Start MySQL service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
    