- name: install and run npm
  hosts: web
  become: yes
  tasks:
    - name: install npm
      ansible.builtin.package:
        name: install npm
        state: present
    - name: install npm
      ansible.builtin.service:
        name: run npm
        state: started