- name: varaibles from file
  hosts: localhost
  connection: local
  vars_files:
    -vars.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, MENTOR is {{TRAINER}}"