172.31.19.131

[web]
172.31.19.131


[backend]
172.31.19.131
172.31.27.168

[local]
localhost

[localhost]
127.0.0.1 ansible_connection=local

[localhost:vars]
COURSE=aws with devops
DURATION=120HRS
TRAINER=SIVA